#!/bin/bash

# php artisan db:seed --class="Works\Eventworks\Seeders\CountrySeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\CitySeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\EventTagSeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\EventCategorySeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\ParticipantSeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\OrganizerSeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\LocationSeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\MediaSeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\EventLinkSeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\CycleSeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\EventSeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\ProgramSeeder"
# php artisan db:seed --class="Works\Eventworks\Seeders\SpeakerSeeder"
php artisan db:seed --class="Works\Eventworks\Seeders\GlobalSeeder"
